# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('iso_codes', models.CharField(max_length=10)),
                ('population', models.IntegerField()),
                ('area', models.IntegerField()),
                ('gdp', models.CharField(max_length=100)),
            ],
        ),
    ]
