# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlOperacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_operador', models.CharField(max_length=100)),
                ('codigo_equipo', models.CharField(max_length=10)),
                ('fecha', models.CharField(max_length=10)),
                ('metros_perforados', models.IntegerField()),
                ('horas_operacion', models.IntegerField()),
                ('turno', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
